routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::livewire('/', 'inventory.search')->name('inventory.search');
Route::livewire('/item/create', 'item.create')->name('item.create');
Route::livewire('/item/{item}', 'item.show')->name('item.show');
Route::livewire('/item', 'item.index')->name('item.index');
Route::livewire('/item/{item}/edit', 'item.edit')->name('item.edit');
Route::livewire('/itementity/create', 'itementity.create')->name('itementity.create');
Route::livewire('/itementity/{itementity}', 'itementity.show')->name('itementity.show');
Route::livewire('/itementity', 'itementity.index')->name('itementity.index');
Route::livewire('/itementity/{itementity}/refill', 'itementity.refill')->name('itementity.refill');
Route::livewire('/itementity/{itementity}/checkout', 'itementity.checkout')->name('itementity.checkout');
Route::livewire('/storagelocation/{storagelocation}/edit', 'storagelocation.edit')->name('storagelocation.edit');
Route::livewire('/storagelocation/create', 'storagelocation.create')->name('storagelocation.create');
Route::livewire('/storagelocation', 'storagelocation.index')->name('storagelocation.index');
Route::livewire('/storagelocation/{location}', 'storagelocation.show')->name('storagelocation.show');

app/Models/Itementity.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Itementity extends Model
{
    public $fillable = [
        'identifier',
        'item_id',
        'consumable',
        'amount',
        'storagelocation_id',
    ];

    //
    public function tags()
    {
        return $this->belongsToMany(Tag::class, 'tag_itementity');
    }

    public function item()
    {
        return $this->belongsTo(Item::class);
    }

    public function image()
    {
        return $this->hasOne(Image::class, 'id', 'image_id');
    }

    public function storagelocation()
    {
        return $this->belongsTo(Storagelocation::class);
    }

    public function getDisplayImageAttribute(): string
    {
        return $this->image ? optional($this->image)->filename : optional($this->item->image)->filename;
    }

    public function getDisplayStatusAttribute(): string {
        if ($this->consumable != 0) {
            if ($this->amount >= 0) {
                return number_format($this->amount, 0, ',', '.') . " Available";
            }
            return "Not Available";
        }

        switch ($this->status) {
            case 0:
                return "Not Available";
                break;
            case 1:
                return "Available";
                break;
            case 2:
                return "Borrowed";
                break;
            case -1:
                return "Lost";
                break;
                                    
            default:
                return "Unknown";
                break;
        }
    }

}

app/Http/Livewire/Inventory/Search.php
<?php

namespace App\Http\Livewire\Inventory;

use App\Models\Itementity;
use App\Models\Storagelocation;
use App\Models\Tag;
use Livewire\Component;
use Livewire\WithPagination;

class Search extends Component
{
    use WithPagination;

    public $search = "";
    public $tag;
    public $location;
    public $selectedIds = [];

    protected $updatesQueryString = ['search', 'tag', 'location'];

    public function mount()
    {
        $this->search = request()->query('search', $this->search);
        $this->tag = request()->query('tag', $this->tag);
        $this->location = request()->query('location', $this->location);

        if (!is_array($this->tag)) {
            $this->tag = [];
        }
        if (!is_array($this->location)) {
            $this->location = [];
        }
    }

    public function addTag(int $id) {
        $this->tag = array_merge($this->tag, [$id]);
    }

    public function removeTag(int $id) {
        $this->tag = array_diff($this->tag, [$id]);
    }

    public function addLocation(int $id) {
        $this->location = array_merge($this->location, [$id]);
    }

    public function removeLocation(int $id) {
        $this->location = array_diff($this->location, [$id]);
    }

    public function render()
    {
        $query = Itementity::with(['item', 'storagelocation', 'image', 'tags']);

        if (isset($this->search) && is_string($this->search)) {
            $query->where(function($query) {
                $query->orWhere('identifier', 'LIKE', '%'.$this->search.'%');
                $query->orWhereHas('storagelocation', function($query) {
                    return $query->where('name', 'LIKE', '%'.$this->search.'%');
                });
                $query->orWhereHas('item', function($query) {
                    return $query->where('name', 'LIKE', '%'.$this->search.'%')
                        ->orWhere('description', 'LIKE', '%'.$this->search.'%');
                });
            });
        }

        // tags
        $selectedTags = collect([]);
        if (is_array($this->tag) && !empty($this->tag)) {
            $selectedTags = Tag::whereIn('id', $this->tag)->get();

            $query->whereHas('tags', function($query) {
                return $query->whereIn('tag_id', $this->tag);
            });
        }

        // storagelocations
        $selectedLocations = collect([]);
        if (is_array($this->location) && !empty($this->location)) {
            $selectedLocations = Storagelocation::whereIn('id', $this->location)->get();

            $query->whereHas('storagelocation', function($query) {
                return $query->whereIn('storagelocation_id', $this->location);
            });
        }

        $itemEntities = $query->paginate(10);

        $selectedItementities = Itementity::whereIn('id', $this->selectedIds)->get();

        return view('livewire.inventory.search', compact(['itemEntities', 'selectedTags', 'selectedLocations', 'selectedItementities']));
    }
}

app/Http/Livewire/Item/Create.php
<?php

namespace App\Http\Livewire\Item;

use App\Models\Item;
use Livewire\Component;

class Create extends Component
{
    public $name;
    public $description;

    public function updated($field)
    {
        $this->validateOnly($field, [
            'name' => 'min:2|unique:items',
            'description' => 'string',
        ]);
    }

    public function saveItem()
    {
        $validatedData = $this->validate([
            'name' => 'required|unique:items|min:2',
            'description' => 'required|string',
        ]);

        Item::create($validatedData);

        return redirect()->route('inventory.search');
    }

    public function render()
    {
        return view('livewire.item.create');
    }
}

app/Http/Livewire/Item/Edit.php
<?php

namespace App\Http\Livewire\Item;

use App\Models\Item;
use Livewire\Component;

class Edit extends Component
{
    public $item;

    public $name;
    public $description;

    public function mount(Item $item) 
    {
        $this->item = $item;
        $this->name = $item->name;
        $this->description = $item->description;
    }

    public function updated($field)
    {
        $this->validateOnly($field, [
            'name' => 'min:2|unique:items',
            'description' => 'string',
        ]);
    }

    public function saveItem()
    {
        $validatedData = $this->validate([
            'name' => 'required|unique:items|min:2',
            'description' => 'required|string',
        ]);

        $this->item->name = $validatedData['name'];
        $this->item->description = $validatedData['description'];

        $this->item->save();

        return redirect()->route('item.show', [
            'item' => $this->item,
        ]);
    }

    public function render()
    {
        return view('livewire.item.edit');
    }
}

app/Http/Livewire/Item/Index.php
<?php

namespace App\Http\Livewire\Item;

use App\Models\Item;
use Livewire\Component;

class Index extends Component
{
    public function mount()
    {

    }

    public function create()
    {
        return redirect()->route('item.create');
    }

    public function render()
    {
        $items = Item::with('image')->get();

        return view(
            'livewire.item.index',
            compact([
                'items'
            ])
        );
    }
}

app/Http/Livewire/Item/Show.php
<?php

namespace App\Http\Livewire\Item;

use App\Models\Item;
use App\Models\Itementity;
use Livewire\Component;

class Show extends Component
{
    public $item;

    public function mount(Item $item) 
    {
        $this->item = $item;
    }

    public function delete() {
        $this->item->delete();
        $this->item->entities()->delete();

        return redirect()->route('inventory.search');
    }

    public function edit() {
        return redirect()->route('item.edit', [
            'item' => $this->item,
        ]);
    }

    public function render()
    {
        return view(
            'livewire.item.show',
        );
    }
}

app/Http/Livewire/Itementity/Checkout.php
<?php

namespace App\Http\Livewire\Itementity;

use App\Models\Itementity;
use Livewire\Component;

class Checkout extends Component
{
    public $entity;
    public $borrowed_by;

    public function mount(Itementity $itementity) 
    {
        $this->entity = $itementity;
        $this->borrowed_by = $itementity->borrowed_by;

        $this->isCheckoutAllowed();
    }

    protected function isCheckoutAllowed()
    {
        if ($this->entity->consumable == 1 || $this->entity->status != 1) {
            return redirect()->route('itementity.show', $this->entity);
        }
    }

    public function updated($field)
    {
        $this->isCheckoutAllowed();

        $this->validateOnly($field, [
            'borrowed_by' => 'min:2',
        ]);
    }

    public function saveEntity()
    {
        $this->isCheckoutAllowed();

        $validatedData = $this->validate([
            'borrowed_by' => 'required|min:2',
        ]);

        $this->entity->borrowed_by = $validatedData['borrowed_by'];
        $this->entity->status = 2;
        $this->entity->save();

        return redirect()->route('itementity.show', $this->entity);
    }

    public function render()
    {
        return view('livewire.itementity.checkout');
    }
}

app/Http/Livewire/Itementity/Create.php
<?php

namespace App\Http\Livewire\Itementity;

use App\Models\Item;
use App\Models\Itementity;
use App\Models\Storagelocation;
use Livewire\Component;

class Create extends Component
{
    public $identifier;
    public $item_id;
    public $consumable = false;
    public $amount;
    public $storagelocation_id;

    public function mount()
    {

    }

    public function updated($field)
    {
        $this->validateOnly($field, [
            'identifier' => 'min:2|unique:itementities',
            'item_id' => 'exists:items,id',
            'consumable' => 'boolean',
            'amount' => 'nullable|integer',
            'storagelocation_id' => 'exists:storagelocations,id',
        ]);
    }

    public function saveEntity()
    {
        $validatedData = $this->validate([
            'identifier' => 'required|min:2|unique:itementities',
            'item_id' => 'required|exists:items,id',
            'consumable' => 'boolean',
            'amount' => 'nullable|integer',
            'storagelocation_id' => 'required|exists:storagelocations,id',
        ]);

        Itementity::create($validatedData);

        return redirect()->route('inventory.search');
    }

    public function render()
    {
        $items = Item::all();
        $storagelocations = Storagelocation::all();

        return view(
            'livewire.itementity.create',
            compact([
                'items',
                'storagelocations'
            ])
        );
    }
}

app/Http/Livewire/Itementity/Index.php
<?php

namespace App\Http\Livewire\Itementity;

use Livewire\Component;
use App\Models\Itementity;

class Index extends Component
{
    public function mount()
    {

    }

    public function create()
    {
        return redirect()->route('itementity.create');
    }

    public function render()
    {
        $itementities = Itementity::with(['item', 'storagelocation', 'image', 'tags'])->get();

        return view(
            'livewire.itementity.index',
            compact([
                'itementities'
            ])
        );
    }
}

app/Http/Livewire/Itementity/Refill.php
<?php

namespace App\Http\Livewire\Itementity;

use App\Models\Itementity;
use Livewire\Component;

class Refill extends Component
{
    public $entity;
    public $amount;

    public function mount(Itementity $itementity) 
    {
        $this->entity = $itementity;
        $this->amount = $itementity->amount;
    }

    public function updated($field)
    {
        $this->validateOnly($field, [
            'amount' => 'integer',
        ]);
    }

    public function saveEntity()
    {
        $validatedData = $this->validate([
            'amount' => 'required|integer',
        ]);

        $this->entity->amount = $validatedData['amount'];
        $this->entity->save();

        return redirect()->route('itementity.show', $this->entity->id);
    }

    public function render()
    {
        return view(
            'livewire.itementity.refill',
        );
    }
}

app/Http/Livewire/Itementity/Show.php
<?php

namespace App\Http\Livewire\Itementity;

use App\Models\Itementity;
use Livewire\Component;

class Show extends Component
{
    public $entity;

    public function mount(Itementity $itementity) 
    {
        $this->entity = $itementity;
    }

    public function lost() {
        $this->entity->status = -1;
        $this->entity->save();
    }

    public function checkout() {
        return redirect()->route('itementity.checkout', $this->entity);
    }

    public function checkin() {
        $this->entity->status = 1;
        $this->entity->save();
    }

    public function pick() {
        $this->entity->amount--;
        $this->entity->save();
    }

    public function delete() {
        $this->entity->delete();
        return redirect()->route('inventory.search');
    }

    public function render()
    {
        return view(
            'livewire.itementity.show',
        );
    }
}

app/Http/Livewire/Storagelocation/Create.php
<?php

namespace App\Http\Livewire\Storagelocation;

use App\Models\Storagelocation;
use Livewire\Component;

class Create extends Component
{
    public $name;
    public $description;

    public function updated($field)
    {
        $this->validateOnly($field, [
            'name' => 'min:2|unique:storagelocations',
            'description' => 'string',
        ]);
    }

    public function saveStorageLocation()
    {
        $validatedData = $this->validate([
            'name' => 'required|unique:storagelocations|min:2',
            'description' => 'required|string',
        ]);

        $storagelocation = Storagelocation::create($validatedData);

        return redirect()->route('storagelocation.show', [
            'storagelocation' => $storagelocation,
        ]);
    }

    public function render()
    {
        return view('livewire.storagelocation.create');
    }
}

app/Http/Livewire/Storagelocation/Edit.php
<?php

namespace App\Http\Livewire\Storagelocation;

use App\Models\Storagelocation;
use Livewire\Component;

class Edit extends Component
{
    public $storagelocation;
    public $name;
    public $description;

    public function mount(Storagelocation $storagelocation)
    {
        $this->storagelocation = $storagelocation;
        $this->name = $storagelocation->name;
        $this->description = $storagelocation->description;
    }

    public function updated($field)
    {
        $this->validateOnly($field, [
            'name' => 'min:2|unique:storagelocations',
            'description' => 'string',
        ]);
    }

    public function saveStoragelocation()
    {
        $validatedData = $this->validate([
            'name' => 'required|unique:storagelocations|min:2',
            'description' => 'required|string',
        ]);

        $this->storagelocation->name = $validatedData['name'];
        $this->storagelocation->description = $validatedData['description'];

        $this->storagelocation->save();

        return redirect()->route('storagelocation.show', [
            'location' => $this->storagelocation,
        ]);
    }

    public function render()
    {
        return view('livewire.storagelocation.edit');
    }
}

app/Http/Livewire/Storagelocation/Index.php
<?php

namespace App\Http\Livewire\Storagelocation;

use App\Models\Storagelocation;
use Livewire\Component;

class Index extends Component
{
    public function mount()
    {

    }

    public function create()
    {
        return redirect()->route('storagelocation.create');
    }

    public function render()
    {
        $storagelocations = Storagelocation::all();

        return view(
            'livewire.storagelocation.index',
            compact([
                'storagelocations'
            ])
        );
    }
}

resources/views/livewire/itementity/checkout.blade.php
<div class="form-container container">
    <h2>@lang('views/itementity/checkout.title')</h2>

    <form wire:submit.prevent="saveEntity">
        <legend>@lang('models/itementitiy.title.singular')</legend>
        <h2>{{ $entity->identifier }}</h2>

        <fieldset>
            <legend>@lang('models/item.title.singular')</legend>
            <a href="{{ route('item.show', $entity->item) }}">{{ $entity->item->name }}</a>
        </fieldset>

        <fieldset>
            <legend>@lang('views/itementity/checkout.borrowed')</legend>
            <input type="text" wire:model.debounce.500ms="borrowed_by">
            <div class="helper-text">
                @error('borrowed_by') <span class="error">{{ $message }}</span> @enderror
            </div>
        </fieldset>

        <button type="submit" class="btn">@lang('views/itementity/checkout.checkout')</button>
        <a class="btn" href="{{ route('itementity.show', $entity) }}">@lang('views/itementity/checkout.cancel')</a>
    </form>
</div>

resources/views/livewire/itementity/create.blade.php
<div class="form-container container">
    <h2>@lang('views/itementity/create.title')</h2>

    <form wire:submit.prevent="saveEntity">
        <fieldset>
            <legend>@lang('models/itementity.attributes.identifier')</legend>
            <input type="text" wire:model.debounce.500ms="identifier">
            <div class="helper-text">
                @error('identifier') <span class="error">{{ $message }}</span> @enderror
            </div>
        </fieldset>

        <fieldset>
            <legend>@lang('models/item.title.singular')</legend>
            <select wire:model.debounce.500ms="item_id">
                <option value="">
                    Select Item
                </option>
                @foreach($items as $item)
                <option value="{{ $item->id }}">{{ $item->name }}</option>
                @endforeach
            </select>
            <div class="helper-text">
                @error('item_id') <span class="error">{{ $message }}</span> @enderror
            </div>
        </fieldset>

        <fieldset>
            <legend>@lang('models/itementity.attributes.consumable')</legend>
            <input type="checkbox" wire:model.debounce.500ms="consumable">
            <div class="helper-text">
                @error('consumable') <span class="error">{{ $message }}</span> @enderror
            </div>
        </fieldset>

        <fieldset>
            <legend>@lang('models/itementity.attributes.amount')</legend>
            <input type="number" wire:model.debounce.500ms="amount">
            <div class="helper-text">
                @error('amount') <span class="error">{{ $message }}</span> @enderror
            </div>
        </fieldset>

        <fieldset>
            <legend>@lang('models/storagelocation.title.singular')</legend>
            <select wire:model.debounce.500ms="storagelocation_id">
                <option value="">
                    Select Storagelocation
                </option>
                @foreach($storagelocations as $storagelocation)
                    <option value="{{ $storagelocation->id }}">{{ $storagelocation->name }}</option>
                @endforeach
            </select>
            <div class="helper-text">
                @error('storagelocation_id') <span class="error">{{ $message }}</span> @enderror
            </div>
        </fieldset>

        <button type="submit" class="btn">@lang('views/itementity/create.submit')</button>
    </form>
</div>

resources/views/livewire/itementity/index.blade.php
<div class="container">
    <div class="flex-container space-evenly">
        <h2>Item Entities</h2>

        <a class="btn create" wire:click="create">Create</a>
    </div>

    <div class="table">
        <div class="table--row">
            <div class="table--cell table--head"></div>
            <div class="table--cell table--head">Identifier</div>
            <div class="table--cell table--head">Status</div>
            <div class="table--cell table--head">Tags</div>
            <div class="table--cell table--head">Location</div>
        </div>
        @foreach ($itementities as $itemEntity)
            <div class="table--row">
                <div class="table--cell table--select">
                </div>
                <div class="table--cell">
                    <a href="{{ route('itementity.show', ['itementity' => $itemEntity ]) }}" class="table--headline">
                        {{ $itemEntity->identifier }}
                    </a>
                    {{ $itemEntity->item->name }}
                </div>
                <div class="table--cell">
                    {{ $itemEntity->display_status }}

                    @if ($itemEntity->borrowed_by)
                        <div class="mt-2">
                            Borrowed by: {{ $itemEntity->borrowed_by }}
                        </div>
                    @endif
                </div>
                <div class="table--cell table--small">
                    <div class="table--inline-head">Tags</div>
                    @foreach($itemEntity->tags as $tag)
                    <a wire:click="addTag({{ $tag->id }})" class="tag">
                        {{ $tag->name }}
                    </a>
                    @endforeach
                </div>
                <div class="table--cell table--small">
                    <div class="table--inline-head">Storagelocation</div>
                    <a wire:click="addLocation({{ $itemEntity->storagelocation->id }})" class="tag">
                        {{ $itemEntity->storagelocation->name }}
                    </a>
                </div>
            </div>
         @endforeach
    </div>
</div>

resources/views/livewire/itementity/refill.blade.php
<div class="form-container container">
    <form wire:submit.prevent="saveEntity">
        <legend>@lang('views/itementity/refill.title')</legend>
        <h2>{{ $entity->identifier }}</h2>

        <fieldset>
            <legend>@lang('models/item.title.singular')</legend>
            {{ $entity->item->name }}
        </fieldset>

        <fieldset>
            <legend>@lang('models/itementity.attributes.amount')</legend>
            <input type="number" wire:model.debounce.500ms="amount">
            <div class="helper-text">
                @error('amount') <span class="error">{{ $message }}</span> @enderror
            </div>
        </fieldset>
        <button type="submit" class="btn">@lang('views/itementity/refill.submit')</button>
    </form>
</div>

resources/views/livewire/itementity/show.blade.php
<div class="form-container container">
    <legend>@lang('views/itementity/show.title')</legend>
    <h2>{{ $entity->identifier }}</h2>

    <fieldset>
        <legend>@lang('views/item/title.singular')</legend>
        <a href="{{ route('item.show', $entity->item) }}">{{ $entity->item->name }}</a>
    </fieldset>

    <fieldset>
        <legend>@lang('views/itementity/checkout.status')</legend>
        {{ $entity->display_status }}
    </fieldset>

    @if ($entity->consumable == 0)
    <fieldset>
        <legend>@lang('views/itementity/checkout.borrowed')</legend>
        {{ $entity->borrowed_by }}
    </fieldset>
    @endif

    <fieldset>
        <legend>@lang('views/storagelocation/title.singular')</legend>
        {{ $entity->storagelocation->name }}
    </fieldset>

    <fieldset>
        <legend>@lang('views/itementity/checkout.consumable')</legend>
        {{ $entity->consumable == 0 ? 'No' : 'Yes' }}
    </fieldset>

    @if ($entity->consumable != 0)
    <fieldset>
        <legend>@lang('views/itementity/checkout.amount')</legend>
        {{ $entity->amount }}
    </fieldset>
    @endif

    <fieldset>
    @if ($entity->consumable != 0)
    <a class="btn" wire:click="pick">@lang('views/itementity/show.pick')Pick a Item</a>
    <a class="btn" href="{{ route('itementity.refill', $entity) }}">@lang('views/itementity/show.refill')Refill</a>
    @else
        @if ($entity->status == 1)
            <a class="btn" wire:click="checkout">@lang('views/itementity/show.checkout')Checkout</a>
        @else
            <a class="btn" wire:click="checkin">@lang('views/itementity/show.checkin')Checkin</a>
        @endif
        <a class="btn" wire:click="lost">@lang('views/itementity/show.lost')Lost</a>
    @endif
    <a class="btn" wire:click="delete">@lang('views/itementity/show.delete')Delete Itementity</a>
    </fieldset>
</div>